services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
      - static_volume:/app/static
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=crovtrade.settings

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - ./media:/app/media
      - /etc/letsencrypt:/etc/letsencrypt:ro # Используем Let's Encrypt
      - /var/www/html:/var/www/html # Для ACME-челленджа (Let's Encrypt)
    depends_on:
      - web

volumes:
  sqlite_data:
  static_volume:
